<script lang="ts">
import { onMounted, onUnmounted, computed, watch, ref, reactive } from 'vue';
import { registerTrack, unregisterTrack, playTrack, togglePlay, addToQueue, state } from '../../modules/player';
import { Parser } from '../../modules/parser';
import type { MediaTrack } from '../../types';

export const handleMediaAction = async (type: string, id: string, host: string, action: string, trackData: Partial<MediaTrack> = {}): Promise<void> => {
  const media: MediaTrack = { type: type as MediaTrack['type'], id, host, ...trackData };
  if (action === 'play') {
    await playTrack(media);
  } else if (action === 'queue') {
    addToQueue(media);
  }
};

// Global listener for <forum-media> tags generated by Parser
if (typeof document !== 'undefined') {
  document.addEventListener('click', (e: MouseEvent) => {
    const target = e.target as HTMLElement;
    const forumMedia = target.closest('forum-media');
    if (forumMedia) {
      e.preventDefault();
      const d = (forumMedia as HTMLElement).dataset;
      const action = 'play'; // Default action for clicking the placeholder
      handleMediaAction(d.type!, d.id!, d.host!, action, {
        title: d.title,
        author: d.author,
        permlink: d.permlink,
        src: d.src,
        cover: d.cover
      });
    }
  });
}
</script>

<script setup lang="ts">
// Global cache for this session to persist resolutions across component unmounts
const sunoCache = reactive<Record<string, { id: string, src: string, cover: string }>>({});

const props = withDefaults(defineProps<{
  media?: MediaTrack | string; // Can be a track object or raw URL
  title?: string;
  author?: string;
  permlink?: string;
  t?: (k: string) => string;
  mode?: 'card' | 'micro';
  hideButtons?: boolean;
  // Fallback data attributes from parser (for non-Vue content bridge)
  dataType?: string;
  dataId?: string;
  dataSrc?: string;
  dataCover?: string;
  dataHost?: string;
  dataTitle?: string;
  dataAuthor?: string;
  dataPermlink?: string;
  dataPending?: string | boolean;
}>(), {
  mode: 'micro',
  hideButtons: false
});

const emit = defineEmits<{
  openTopic: [post: { author: string; permlink: string }];
}>();

// Internal state for resolved data if we started as pending
const resolvedTrack = ref<MediaTrack | null>(null);
const isResolving = ref(false);
const lastResolvedId = ref<string | null>(null);

const isSunoUuid = (type: string, id: string) => type === 'audio' && id.length >= 32;

const trackData = computed<MediaTrack>(() => {
  // 1. Resolve base data (resolvedTrack > props.media > single props)
  let base: Partial<MediaTrack> = {};
  if (resolvedTrack.value) {
    base = { ...resolvedTrack.value };
  } else if (props.media) {
    if (typeof props.media === 'string') {
      const detected = Parser.detectMedia(props.media);
      if (detected) base = { ...detected };
    } else {
      base = { ...props.media };
    }
  } else {
    base = {
      type: (props.dataType as any) || 'audio',
      id: props.dataId || '',
      src: props.dataSrc,
      cover: props.dataCover,
      host: props.dataHost,
      author: props.dataAuthor,
      permlink: props.dataPermlink,
      title: props.dataTitle
    };
  }
  
  const type = base.type || 'audio';
  const id = base.id || '';
  let src = base.src;
  let cover = base.cover;

  if (isSunoUuid(type, id)) {
    if (!src) src = `https://cdn1.suno.ai/${id}.mp3`;
    if (!cover) cover = `https://cdn2.suno.ai/image_large_${id}.jpeg`;
  }

  // Auto-generate YouTube thumbnail if missing
  if (type === 'youtube' && !cover) {
    cover = `https://img.youtube.com/vi/${id}/0.jpg`;
  }

  // Title logic: Prefer real titles over placeholders. 
  // props.title (from thread list) should have high priority.
  let title = base.title || props.title || props.dataTitle || '';
  if (!title || title === '(no title)' || title === 'Media Content') {
    if (props.title && props.title !== '(no title)') title = props.title;
    else if (props.dataTitle && props.dataTitle !== '(no title)') title = props.dataTitle;
    else if (base.title && base.title !== '(no title)') title = base.title;
    else title = 'Media Content';
  }

  // Smarter pending logic: ignore props if we already have src or it's a UUID
  const dataPending = base.pending || props.dataPending === 'true' || props.dataPending === true;
  const actuallyPending = dataPending && !src && !isSunoUuid(type, id) && type !== 'youtube';

  return {
    type,
    id,
    src: src || undefined,
    cover: cover || undefined,
    host: base.host || props.dataHost || undefined,
    title,
    author: base.author || props.author || props.dataAuthor || 'post',
    permlink: base.permlink || props.permlink || props.dataPermlink || '',
    pending: !resolvedTrack.value && (isResolving.value || actuallyPending),
  };
});

// Self-resolution for pending tracks
const resolveIfNeeded = async () => {
  const currentId = trackData.value.id;
  if (!currentId || currentId === lastResolvedId.value) return;

  // Immediate exit if it's already a full UUID or has a source - NO RESOLVING NEEDED
  if (isSunoUuid(trackData.value.type, currentId) || trackData.value.src) {
    lastResolvedId.value = currentId;
    return;
  }

  // If already resolving, just exit
  if (isResolving.value) return;

  // We resolve if marked as pending OR if it's a PeerTube track without a confirmed resolution
  const isSunoPending = trackData.value.type === 'audio' && trackData.value.pending;
  const isPeertubeNeeded = trackData.value.type === 'peertube' && !resolvedTrack.value;

  if (!isSunoPending && !isPeertubeNeeded) {
    lastResolvedId.value = currentId;
    return;
  }

  // 0. Check module-level cache first
  if (trackData.value.type === 'audio' && sunoCache[currentId]) {
    const cached = sunoCache[currentId];
    console.log('[ForumMedia] Using module cache for:', currentId);
    resolvedTrack.value = { ...trackData.value, ...cached, pending: false };
    lastResolvedId.value = currentId;
    return;
  }

  // 1. Check if we already have this resolved in global state
  const existing = state.autoQueue.find(t => 
    t.id === currentId && 
    t.type === trackData.value.type && 
    !t.pending && 
    (t.src || t.cover)
  );
  
  if (existing) {
    console.log('[ForumMedia] Using autoQueue cache for:', currentId);
    resolvedTrack.value = { ...existing, pending: false };
    lastResolvedId.value = currentId;
    return;
  }

  console.log('[ForumMedia] Resolving:', currentId);
  lastResolvedId.value = currentId;
  isResolving.value = true;
  try {
    // Logic moved from Parser for better independence
    let resolved: MediaTrack | null = null;
    
    if (trackData.value.type === 'audio' && !trackData.value.src && currentId.length < 30) {
      // Suno resolution
      const url = `https://suno.com/s/${currentId}`;
      const proxyUrl = `https://corsproxy.io/?${encodeURIComponent(url)}`;
      const response = await fetch(proxyUrl);
      const text = await response.text();
      const uuidMatch = text.match(/song\/([a-f0-9-]{36})/i);
      if (uuidMatch) {
        const uuid = uuidMatch[1];
        resolved = { 
          ...trackData.value, 
          id: uuid, 
          src: `https://cdn1.suno.ai/${uuid}.mp3`, 
          cover: `https://cdn2.suno.ai/image_large_${uuid}.jpeg`,
          pending: false 
        };
      }
    } else if (trackData.value.type === 'peertube' && !trackData.value.cover) {
      // PeerTube resolution
      const host = trackData.value.host || 'blurt.media';
      const apiUrl = `https://${host}/api/v1/videos/${currentId}`;
      const proxyUrl = `https://corsproxy.io/?${encodeURIComponent(apiUrl)}`;
      const response = await fetch(proxyUrl);
      if (response.ok) {
        const data = await response.json();
        const cover = data.thumbnailPath ? `https://${host}${data.thumbnailPath}` : (data.previewPath ? `https://${host}${data.previewPath}` : null);
        if (cover) {
          resolved = { ...trackData.value, cover, pending: false };
        }
      }
    }

    if (resolved) {
      resolvedTrack.value = resolved;
      // Save to module-level cache if it was a resolution (short ID -> long ID)
      if (trackData.value.type === 'audio' && currentId.length < 30 && resolved.id.length >= 32) {
        sunoCache[currentId] = { id: resolved.id, src: resolved.src!, cover: resolved.cover! };
      }
    }
  } catch (e) { 
    console.error('ForumMedia: Resolution failed', e); 
  } finally { 
    isResolving.value = false; 
  }
};

const isActive = computed(() => {
  const current = state.currentTrack;
  if (!current) return false;
  
  // Match by ID and Type. 
  // For Suno, we might have a short ID in the component and a long ID in the player.
  if (current.id === trackData.value.id && current.type === trackData.value.type) return true;
  
  // Fallback: If this is a Suno track, check if the resolved ID matches
  if (trackData.value.type === 'audio' && lastResolvedId.value === current.id) return true;
  
  return false;
});

const isPlaying = computed(() => isActive.value && state.playing);

let registeredId: string | null = null;
let registeredType: string | null = null;

const syncTrack = () => {
  // Register if we have an ID AND (it's not pending OR we already have a cover)
  // This allows tracks with covers from blockchain metadata to appear immediately.
  const shouldRegister = trackData.value.id && (!trackData.value.pending || trackData.value.cover);
  
  if (shouldRegister) {
    if (registeredId && (registeredId !== trackData.value.id || registeredType !== trackData.value.type)) {
      unregisterTrack(registeredId, registeredType!);
    }
    registerTrack(trackData.value);
    registeredId = trackData.value.id;
    registeredType = trackData.value.type;
  } else if (registeredId) {
    unregisterTrack(registeredId, registeredType!);
    registeredId = null;
    registeredType = null;
  }
};

onMounted(() => {
  syncTrack();
  resolveIfNeeded();
});

watch(() => [trackData.value.id, trackData.value.pending, trackData.value.cover], () => {
  syncTrack();
  resolveIfNeeded();
});

onUnmounted(() => {
  if (registeredId && registeredType) {
    unregisterTrack(registeredId, registeredType);
  }
});

const handlePlay = async () => {
  if (isResolving.value) return;

  // If we are pending, we MUST resolve before playing
  if (trackData.value.pending) {
    await resolveIfNeeded();
  }
  
  if (isActive.value) {
    togglePlay();
  } else {
    playTrack(trackData.value);
  }
};

const handleQueue = () => {
  if (trackData.value.pending || isResolving.value) return;
  addToQueue(trackData.value);
};

const thumbUrl = computed(() => trackData.value.cover || '');

const sourceLabel = computed(() => {
  if (trackData.value.pending) return 'resolving...';
  return trackData.value.host || (trackData.value.type === 'audio' ? 'suno' : trackData.value.type);
});

</script>

<template>
  <div 
    class="forum-media-container" 
    :class="[`mode-${mode}`, { 'is-active': isActive, 'is-playing': isPlaying }]"
  >
    <!-- MICRO MODE -->
    <template v-if="mode === 'micro'">
      <div class="forum-media-micro">
        <slot>
          <template v-if="!hideButtons">
            <span class="media-icon" @click.stop="handlePlay" :title="trackData.title" :class="{ 'is-active': isActive, 'is-playing': isPlaying }">
              <i v-if="isResolving" class="fa-solid fa-spinner fa-spin"></i>
              <i v-else :class="isPlaying ? 'fa-solid fa-pause' : (trackData.type === 'audio' ? 'fa-solid fa-music' : 'fa-solid fa-circle-play')"></i>
            </span>
            <span class="media-icon" @click.stop="handleQueue">
              <i class="fa-solid fa-plus"></i>
            </span>
          </template>
        </slot>
      </div>
    </template>

    <!-- CARD MODE -->
    <template v-else-if="mode === 'card'">
      <div 
        class="media-placeholder" 
        :class="{ 'is-resolving': trackData.pending, 'no-thumb': !thumbUrl }"
        :style="thumbUrl ? `background-image: url(${thumbUrl})` : ''"
      >
        <div class="media-placeholder-overlay">
          <div class="media-placeholder-actions">
            <button class="btn btn-primary" @click.stop="handlePlay" :disabled="trackData.pending">
              <i v-if="trackData.pending" class="fa-solid fa-spinner fa-spin"></i>
              <i v-else :class="isPlaying ? 'fa-solid fa-pause' : 'fa-solid fa-play'"></i> 
              <span class="btn-text">{{ isPlaying ? 'Pause' : 'Play' }}</span>
            </button>
            <button class="btn btn-ghost" @click.stop="handleQueue" :disabled="trackData.pending">
              <i class="fa-solid fa-plus"></i> <span class="btn-text">Queue</span>
            </button>
          </div>
          <div class="source-label">{{ sourceLabel }}</div>
        </div>
      </div>
    </template>
  </div>
</template>

<style scoped>
/* Re-inject essential global styles for Shadow DOM */
.btn {
  padding: 6px 14px;
  font-size: 13px;
  font-weight: bold;
  cursor: pointer;
  border: 1px solid var(--input-border, #999);
  background: var(--input-bg, #fff);
  color: var(--text, #333);
  border-radius: 4px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 6px;
  text-decoration: none;
  transition: all 0.2s;
}
.btn:hover { background: var(--bg-white, #fff); border-color: var(--primary, #006699); color: var(--primary, #006699); }
.btn-primary { background: var(--primary, #006699); color: #fff; border-color: var(--primary-dk, #005580); }
.btn-primary:hover { background: var(--primary-lt, #0076B1); color: #fff; }
.btn-ghost { background: transparent; color: var(--primary, #006699); border: 1px solid var(--primary, #006699); }
.btn-ghost:hover { background: var(--primary, #006699); color: #fff; }
.btn:disabled { opacity: .5; cursor: default; }

.forum-media-container {
  display: block;
  width: 100%;
  max-width: 100%;
  box-sizing: border-box;
}

.mode-micro.forum-media-container {
  display: inline-block;
  vertical-align: middle;
  width: auto;
}

.forum-media-micro {
  display: flex;
  align-items: center;
  gap: 4px;
}

.media-icon {
  cursor: pointer;
  color: var(--primary, #006699);
  opacity: 0.7;
  transition: opacity 0.2s;
  font-size: 14px;
}
.media-icon:hover { opacity: 1; }

.forum-media-container.mode-card {
  display: block;
  width: 100%;
  max-width: 100%;
  clear: both;
}

.media-placeholder {
  position: relative;
  width: 100%;
  aspect-ratio: 16 / 9;
  background-color: #000;
  background-size: cover;
  background-position: center;
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid var(--border-main, #98AAB1);
  box-sizing: border-box;
}

.media-placeholder-overlay {
  position: absolute;
  top: 0; left: 0; right: 0; bottom: 0;
  background: rgba(0,0,0,0.5);
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  opacity: 0.9;
  transition: opacity 0.3s;
}

.media-placeholder-actions {
  display: flex;
  gap: 12px;
  justify-content: center;
  width: 100%;
  padding: 0 10px;
  box-sizing: border-box;
}

.source-label {
  position: absolute;
  bottom: 10px;
  right: 12px;
  font-size: 10px;
  text-transform: uppercase;
  color: #fff;
  opacity: 0.8;
  background: rgba(0,0,0,0.4);
  padding: 2px 6px;
  border-radius: 4px;
}

.media-placeholder.is-resolving {
  filter: grayscale(0.5);
  cursor: wait;
  animation: bfp-resolving-pulse 2s infinite ease-in-out;
}
@keyframes bfp-resolving-pulse {
  0% { opacity: 0.8; }
  50% { opacity: 0.4; }
  100% { opacity: 0.8; }
}

@media (max-width: 800px) {
  .media-placeholder-actions {
    flex-direction: column;
    gap: 8px;
    align-items: center;
  }
  .btn {
    width: 100%;
    max-width: 160px;
  }
  .btn-text { display: inline; }
}

@media (max-width: 480px) {
  .forum-media-container.mode-card {
    max-width: calc(100vw - 32px);
  }
}
</style>
